#!/usr/bin/env node

const program = require('commander');
// Require logic.js file and extract controller functions using JS destructuring assignment
const { addSetup, getSetup, setDefaultProject } = require('./logic');
const { makeSetup, debug } = require('./firebase')

program
  .version('0.0.1')
  .description('Firebase debugger CLI helper');

program
  .command('debug <function>')
  .alias('d')
  .description('debug a function')
  .action(functionName => {
    debug(functionName)
  });

program
  .command('config')
  .alias('c')
  .option('-P, --project <project>', 'the project name you are configuring')
  .description('Get setup from firebase')
  .action(async (options) => {
    addSetup(options.project, await makeSetup())
  });

program
  .command('set <project>')
  .alias('s')
  .description('setup default project')
  .action((project) => {
    setDefaultProject(project)
  });

program
  .command('getSetup <name>')
  .alias('r')
  .description('Get contact')
  .action(name => getSetup(name));

// Assert that a VALID command is provided 
if (!process.argv.slice(2).length || !/[arudl]/.test(process.argv.slice(2))) {
  program.outputHelp();
  process.exit();
}
program.parse(process.argv);